CREATE TABLE dbo.Address
(
	AddressKey INT IDENTITY CONSTRAINT PK_Address PRIMARY KEY,
	AddressLine1 NVARCHAR(50) NULL,
	AddressLine2 NVARCHAR(50) NULL,
	City NVARCHAR(50) NULL,
	[State] INT NULL,
	ZipCode NVARCHAR(12) NULL,
	ValidFromDateTime DATETIME2(7) GENERATED ALWAYS AS ROW START NOT NULL,
	ValidToDateTime DATETIME2(7) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL, 
    [Hello] AS 'Hello WOrld',
	PERIOD FOR SYSTEM_TIME (ValidFromDateTime, ValidToDateTime)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Address_History));
GO
