CREATE TABLE dbo.AllTypes
    (
      Id INT NOT NULL
             PRIMARY KEY ,
      RowName VARCHAR(100) NOT NULL
                           UNIQUE ,
      CharNull CHAR(10) NULL ,
      CharNotNull CHAR(10) NOT NULL ,
      VarCharNull VARCHAR(10) NULL ,
      VarCharNotNull VARCHAR(10) NOT NULL ,
      NCharNull CHAR(10) NULL ,
      NCharNotNull CHAR(10) NOT NULL ,
      NVarCharNull VARCHAR(10) NULL ,
      NVarCharNotNull VARCHAR(10) NOT NULL ,
      BitNull BIT NULL ,
      BitNotNull BIT NOT NULL ,
      TinyIntNull TINYINT NULL ,
      TinyIntNotNull TINYINT NOT NULL ,
      IntNull INT NULL ,
      IntNotNull INT NOT NULL ,
      BigIntNull BIGINT NULL ,
      BigIntNotNull BIGINT NOT NULL ,
      NumericNull NUMERIC NULL ,
      NumericNotNull NUMERIC NOT NULL ,
      SmallIntNull SMALLINT NULL ,
      SmallIntNotNull SMALLINT NOT NULL ,
      DecimalNull DECIMAL NULL ,
      DecimalNotNull DECIMAL NOT NULL ,
      SmallMoneyNull SMALLMONEY NULL ,
      SmallMoneyNotNull SMALLMONEY NOT NULL ,
      MoneyNull MONEY NULL ,
      MoneyNotNull MONEY NOT NULL ,
      FloatNull FLOAT NULL ,
      FloatNotNull FLOAT NOT NULL ,
      RealNull REAL NULL ,
      RealNotNull REAL NOT NULL ,
      DateNull DATE NULL ,
      DateNotNull DATE NOT NULL ,
      DatetimeoffsetNull DATETIMEOFFSET NULL ,
      DatetimeoffsetNotNull DATETIMEOFFSET NOT NULL ,
      Datetime2Null DATETIME2 NULL ,
      Datetime2NotNull DATETIME2 NOT NULL ,
      SmalldatetimeNull SMALLDATETIME NULL ,
      SmalldatetimeNotNull SMALLDATETIME NOT NULL ,
      DatetimeNull DATETIME NULL ,
      DatetimeNotNull DATETIME NOT NULL ,
      TimeNull TIME NULL ,
      TimeNotNull TIME NOT NULL ,
      TextNull TEXT NULL ,
      TextNotNull TEXT NOT NULL ,
      NTextNull NTEXT NULL ,
      NTextNotNull NTEXT NOT NULL ,
      BinaryNull BINARY(20) NULL ,
      BinaryNotNull BINARY(20) NOT NULL ,
      VarBinaryNull VARBINARY(20) NULL ,
      VarBinaryNotNull VARBINARY(20) NOT NULL ,
      ImageNull IMAGE NULL ,
      ImageNotNull IMAGE NOT NULL ,
      TimestampNotNull TIMESTAMP NOT NULL ,
      UniqueidentifierNull UNIQUEIDENTIFIER NULL ,
      UniqueidentifierNotNull UNIQUEIDENTIFIER NOT NULL ,
      XmlNull XML NULL ,
      XmlNotNull XML NOT NULL,
      CharOneNull CHAR(1) NULL ,
      CharOneNotNull CHAR(1) NOT NULL 
    );
